cmake_minimum_required(VERSION 3.19)

if(NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "OUTPUT_DIR is required. Usage: cmake -DOUTPUT_DIR=<output_directory> -P download_model.cmake")
endif()

set(IPT_MODEL_RELEASE_TAG "v0-models")
set(IPT_MODELS_RELEASE_API_URL "https://api.github.com/repos/Ircam-Partiels/ipt-vamp-plugin/releases/tags/${IPT_MODEL_RELEASE_TAG}")
set(IPT_MODELS_DIR "${OUTPUT_DIR}/models")
set(IPT_MODELS_RELEASE_JSON "${OUTPUT_DIR}/ipt_release.json")
file(MAKE_DIRECTORY "${IPT_MODELS_DIR}")

file(DOWNLOAD "${IPT_MODELS_RELEASE_API_URL}" "${IPT_MODELS_RELEASE_JSON}" STATUS DOWNLOAD_STATUS)
list(GET DOWNLOAD_STATUS 0 STATUS_CODE)
if(NOT STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "Failed to fetch release metadata: ${DOWNLOAD_STATUS}")
endif()

file(READ "${IPT_MODELS_RELEASE_JSON}" IPT_MODELS_RELEASE_CONTENT)
string(JSON ASSET_COUNT LENGTH "${IPT_MODELS_RELEASE_CONTENT}" assets)
math(EXPR LAST_INDEX "${ASSET_COUNT}-1")

foreach(i RANGE ${LAST_INDEX})
  string(JSON ASSET_NAME GET "${IPT_MODELS_RELEASE_CONTENT}" assets ${i} name)
  if(ASSET_NAME MATCHES "\\.ts$")
    string(JSON ASSET_URL GET "${IPT_MODELS_RELEASE_CONTENT}" assets ${i} browser_download_url)
    set(DEST "${IPT_MODELS_DIR}/${ASSET_NAME}")
    if(NOT EXISTS "${DEST}")
      message(STATUS "Downloading model ${ASSET_NAME}")
      file(DOWNLOAD "${ASSET_URL}" "${DEST}" STATUS DOWNLOAD_STATUS)
      list(GET DOWNLOAD_STATUS 0 STATUS_CODE)
      if(NOT STATUS_CODE EQUAL 0)
        message(FATAL_ERROR "Failed downloading ${ASSET_NAME}: ${DOWNLOAD_STATUS}")
      endif()
    else()
      message(STATUS "${ASSET_NAME} already exists")
    endif()
  endif()
endforeach()